### ISSUE TITLE
Говнокод

### ISSUE THREAD

**Issue by AlexandrUkr** [mrlinqu/Templater#1]
Читаем на ночь: https://secure.php.net/manual/index.php и всё у Вас будет хорошо!

А тут я вообще упал

``` php
 while( preg_match( '/{%\s*extends\s+(\S+)\s*%}/is', $template, $ext_matches ) )
        {}
```

Чувак ты комик спасибо за поднятие чувства юмора)))

**Comment by mrlinqu** [comment]
Читаем с утреца, для лучшего понимания, https://ru.wikipedia.org/wiki/Регулярные_выражения и не падаем в обморок от непонятных конструкций.
Так же для просвещения читаем https://ru.wikipedia.org/wiki/Хамство и https://ru.wiktionary.org/wiki/наглость

**Comment by AlexandrUkr** [comment]
Падает в обморок php интерпретатор когда видит как программист усложняет до боли простую задачу, написать что б работало это не вариант, нужно еще и за оптимизацией следить, советую тестировать свой код на скорость выполнения <a href="http://php.net/manual/en/function.microtime.php">Script Time</a>
Так же советую не отставать от жизни так как сейчас уже php 7.0 а Вы еще сидите в 5.3 ибо Вы знаток регулярных выражений не читаете что для обратного вызова используют не preg_replace а preg_replace_callback, научитесь принимать критику

**Comment by mrlinqu** [comment]
Откройте курсы по изучению как нужно писать правильный код на PHP, оптимизации времени выполнения и тестированию - озолотитесь на советах.

Бесплатный совет: прежде чем сувать нос в репо, который вас не касается, и учить жизни других людей, для начала стоит посмотреть даты последних коммитов и узнать цели этих проектов.
